         Console.ForegroundColor = ConsoleColor.DarkGreen;
Console.Write("+"); 
            Thread.Sleep(500);
Console.Write("-"); 
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.WriteLine("+");
            Thread.Sleep(500);
Console.Write("|");
            Thread.Sleep(500);
            Console.ResetColor();
Console.Write(" ");
            Thread.Sleep(500);
            Console.ForegroundColor = ConsoleColor.Red;
Console.Write("A");
            Thread.Sleep(500);
Console.Write("n");
            Thread.Sleep(500);
Console.Write("d");
            Thread.Sleep(500);
Console.Write("r");
            Thread.Sleep(500);
Console.Write("é");
            Thread.Sleep(500);
            Console.ResetColor();
            Console.ForegroundColor = ConsoleColor.Green;
Console.Write(" ");
            Thread.Sleep(500);
Console.WriteLine("|");
Console.Write("+"); 
            Thread.Sleep(500);
Console.Write("-"); 
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.Write("-");
            Thread.Sleep(500);
Console.WriteLine("+");
            Console.ResetColor();